### PR TITLE
Add support for riscv64

### PR DESCRIPTION
**Pull request by rwmjones**

### CODE REVIEW

**Comment by rwmjones** [comment]
@davidlt

**Comment by bcl** [comment]
Is that really all it needs? If so, that's great. But I want to be double extra sure someone has built and tested it first :)

**Comment by rfinnie** [comment]
Can confirm, builds and runs on riscv64 just fine, and has been building by Debian riscv64 for awhile now (the Debian packaging just doesn't use LIBDIR in this case so it was never noticed).

**Comment by rwmjones** [comment]
We've been building this package in RISC-V for a while: http://fedora.riscv.rocks/koji/packageinfo?packageID=14693

**Pull request merged**
